site_name: Kubescape
site_url: https://kubescape.io/
repo_url: https://github.com/kubescape/kubescape
theme:
  name: material
  logo: assets/kubescape-lockup.svg
  font:
    text: Fira Sans
    code: Fira Mono
  features:
    - content.code.copy
    - navigation.tabs    
    - navigation.footer  
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/@kubescape
    - icon: fontawesome/brands/github 
      link: https://github.com/kubescape/kubescape
  analytics:
    provider: google
    property: G-BS68QKB4RT
extra_css:
  - stylesheets/extra.css
copyright:
  Copyright &copy; 2021 - 2023 <a href="https://kubescape.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1">The Kubescape Authors</a>

nav:
    - Home: 'index.md'
    - Docs:
        - 'Documentation overview': 'docs/index.md'
        - 'Getting Started': 'docs/getting-started.md'
        - 'Installing the client': 'docs/install-cli.md'
        - 'Installing in your cluster': 'docs/install-in-cluster.md'
        - 'Scanning your environment': 'docs/scanning.md'
        - 'Customizing your scans': 'docs/customizing-your-scans.md'
        - 'Accepting risk': 'docs/accepting-risk.md'
        - 'Connecting to providers': 'docs/providers.md'
        - Integrations:
            - 'GitHub': 'docs/integrations/github.md'
            - 'Lens': 'docs/integrations/lens.md'
        - 'Building Kubescape': 'docs/building.md'
    - Project: 
        - 'About the Kubescape project': 'project/about.md'
        - 'License': 'project/license.md'
        - 'Community': 'project/community.md'
        - 'Contributing': 'https://github.com/kubescape/kubescape/blob/master/CONTRIBUTING.md'
    - GitHub: 'https://github.com/kubescape/kubescape'

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences