name: Auto-approve Controls Documentation changes

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'TRohit20'
    steps:
      - uses: hmarr/auto-approve-action@v3