name: Auto-merge PR syncing documentation

on:
  pull_request:
    types: [labeled]
    branches:
      - main/* 

jobs:
  run_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically Merge PR
        uses: plm9606/automerge_actions@1.2.2
        with:
          label-name: automerge
          reviewers-number: 0
          merge-method: merge
          auto-delete: false
          github-token: ${{ secrets.PAT }}