name: Merge Bot

on:
  pull_request:
    types:
      - labeled
  pull_request_review:
    types:
      - submitted

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@v0.1.0
      with:
        test: false
        reviewers: false
        labels: automerge
        # checks_enabled: false
        method: merge